


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "bronze";


ALTER SCHEMA "bronze" OWNER TO "postgres";


CREATE SCHEMA IF NOT EXISTS "gold";


ALTER SCHEMA "gold" OWNER TO "postgres";


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE SCHEMA IF NOT EXISTS "silver";


ALTER SCHEMA "silver" OWNER TO "postgres";


CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."log_queries"() RETURNS "event_trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    INSERT INTO query_logs (query, executed_at)
    VALUES (current_query(), NOW());
END;
$$;


ALTER FUNCTION "public"."log_queries"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "bronze"."rightmove_data_brz" (
    "id" integer NOT NULL,
    "Property Address" "text",
    "Agent Address" "text",
    "Agent Name" "text",
    "Available Date" "text",
    "Property Type" "text",
    "Bedrooms" numeric,
    "Bathrooms" numeric,
    "Post Date" "text",
    "Price" "text",
    "Latitude" double precision,
    "Longitude" double precision,
    "URL" "text"
);


ALTER TABLE "bronze"."rightmove_data_brz" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "bronze"."rightmove_data_brz_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "bronze"."rightmove_data_brz_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "bronze"."rightmove_data_brz_id_seq" OWNED BY "bronze"."rightmove_data_brz"."id";



CREATE TABLE IF NOT EXISTS "silver"."agents_df" (
    "id" integer NOT NULL,
    "agent_name" "text",
    "rowid" "text",
    "locations_df_id" integer
);


ALTER TABLE "silver"."agents_df" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "silver"."locations_df" (
    "id" integer NOT NULL,
    "full_address" "text",
    "latitude" double precision,
    "longitude" double precision,
    "property_address" "text",
    "rowid" "text"
);


ALTER TABLE "silver"."locations_df" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."agents_locations" AS
 SELECT "a"."id" AS "agent_id",
    "a"."agent_name",
    "a"."rowid",
    "a"."locations_df_id",
    "l"."latitude",
    "l"."longitude",
    "l"."full_address",
    "l"."property_address"
   FROM ("silver"."agents_df" "a"
     JOIN "silver"."locations_df" "l" ON (("a"."rowid" = "l"."rowid")));


ALTER VIEW "public"."agents_locations" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."auth_group" (
    "id" integer NOT NULL,
    "name" character varying(150) NOT NULL
);


ALTER TABLE "public"."auth_group" OWNER TO "postgres";


ALTER TABLE "public"."auth_group" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_group_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_group_permissions" (
    "id" bigint NOT NULL,
    "group_id" integer NOT NULL,
    "permission_id" integer NOT NULL
);


ALTER TABLE "public"."auth_group_permissions" OWNER TO "postgres";


ALTER TABLE "public"."auth_group_permissions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_group_permissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_permission" (
    "id" integer NOT NULL,
    "name" character varying(255) NOT NULL,
    "content_type_id" integer NOT NULL,
    "codename" character varying(100) NOT NULL
);


ALTER TABLE "public"."auth_permission" OWNER TO "postgres";


ALTER TABLE "public"."auth_permission" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_permission_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_user" (
    "id" integer NOT NULL,
    "password" character varying(128) NOT NULL,
    "last_login" timestamp with time zone,
    "is_superuser" boolean NOT NULL,
    "username" character varying(150) NOT NULL,
    "first_name" character varying(150) NOT NULL,
    "last_name" character varying(150) NOT NULL,
    "email" character varying(254) NOT NULL,
    "is_staff" boolean NOT NULL,
    "is_active" boolean NOT NULL,
    "date_joined" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."auth_user" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."auth_user_groups" (
    "id" bigint NOT NULL,
    "user_id" integer NOT NULL,
    "group_id" integer NOT NULL
);


ALTER TABLE "public"."auth_user_groups" OWNER TO "postgres";


ALTER TABLE "public"."auth_user_groups" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_user_groups_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."auth_user" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_user_user_permissions" (
    "id" bigint NOT NULL,
    "user_id" integer NOT NULL,
    "permission_id" integer NOT NULL
);


ALTER TABLE "public"."auth_user_user_permissions" OWNER TO "postgres";


ALTER TABLE "public"."auth_user_user_permissions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_user_user_permissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."backend_todo" (
    "id" bigint NOT NULL,
    "title" character varying(200) NOT NULL,
    "description" "text" NOT NULL,
    "completed" boolean NOT NULL
);


ALTER TABLE "public"."backend_todo" OWNER TO "postgres";


ALTER TABLE "public"."backend_todo" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."backend_todo_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_admin_log" (
    "id" integer NOT NULL,
    "action_time" timestamp with time zone NOT NULL,
    "object_id" "text",
    "object_repr" character varying(200) NOT NULL,
    "action_flag" smallint NOT NULL,
    "change_message" "text" NOT NULL,
    "content_type_id" integer,
    "user_id" integer NOT NULL,
    CONSTRAINT "django_admin_log_action_flag_check" CHECK (("action_flag" >= 0))
);


ALTER TABLE "public"."django_admin_log" OWNER TO "postgres";


ALTER TABLE "public"."django_admin_log" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_admin_log_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_content_type" (
    "id" integer NOT NULL,
    "app_label" character varying(100) NOT NULL,
    "model" character varying(100) NOT NULL
);


ALTER TABLE "public"."django_content_type" OWNER TO "postgres";


ALTER TABLE "public"."django_content_type" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_content_type_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_migrations" (
    "id" bigint NOT NULL,
    "app" character varying(255) NOT NULL,
    "name" character varying(255) NOT NULL,
    "applied" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."django_migrations" OWNER TO "postgres";


ALTER TABLE "public"."django_migrations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_migrations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_session" (
    "session_key" character varying(40) NOT NULL,
    "session_data" "text" NOT NULL,
    "expire_date" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."django_session" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."properties" (
    "id" integer NOT NULL,
    "property_type" "text",
    "bedrooms" "text",
    "bathrooms" "text",
    "locations_df_sil_id" integer,
    "agents_df_sil_id" integer
);


ALTER TABLE "public"."properties" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."properties1" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "property_type" "text",
    "bedrooms" "text",
    "bathrooms" "text"
);


ALTER TABLE "public"."properties1" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."properties_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."properties_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."properties_id_seq" OWNED BY "public"."properties"."id";



CREATE TABLE IF NOT EXISTS "public"."query_logs" (
    "id" integer NOT NULL,
    "query" "text" NOT NULL,
    "executed_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."query_logs" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."query_logs_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."query_logs_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."query_logs_id_seq" OWNED BY "public"."query_logs"."id";



CREATE SEQUENCE IF NOT EXISTS "silver"."agents_df_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "silver"."agents_df_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "silver"."agents_df_id_seq" OWNED BY "silver"."agents_df"."id";



CREATE TABLE IF NOT EXISTS "silver"."agents_df_sil" (
    "id" integer NOT NULL,
    "agent_name" "text",
    "agent_address" "text"
);


ALTER TABLE "silver"."agents_df_sil" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "silver"."agents_df_sil_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "silver"."agents_df_sil_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "silver"."agents_df_sil_id_seq" OWNED BY "silver"."agents_df_sil"."id";



CREATE TABLE IF NOT EXISTS "silver"."listings_df" (
    "id" integer NOT NULL,
    "parsed_post_date" "text",
    "parsed_available_date" timestamp without time zone,
    "monthly_price" "text",
    "listing_id" "text",
    "url" "text",
    "rowid" "text",
    "properties_df_sil_id" integer
);


ALTER TABLE "silver"."listings_df" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "silver"."listings_df_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "silver"."listings_df_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "silver"."listings_df_id_seq" OWNED BY "silver"."listings_df"."id";



CREATE TABLE IF NOT EXISTS "silver"."listings_df_sil" (
    "id" integer NOT NULL,
    "parsed_post_date" "text",
    "parsed_available_date" "text",
    "monthly_price" "text",
    "listing_id" "text",
    "url" "text",
    "properties_df_sil_id" integer
);


ALTER TABLE "silver"."listings_df_sil" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "silver"."listings_df_sil_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "silver"."listings_df_sil_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "silver"."listings_df_sil_id_seq" OWNED BY "silver"."listings_df_sil"."id";



CREATE SEQUENCE IF NOT EXISTS "silver"."locations_df_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "silver"."locations_df_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "silver"."locations_df_id_seq" OWNED BY "silver"."locations_df"."id";



CREATE TABLE IF NOT EXISTS "silver"."locations_df_sil" (
    "id" integer NOT NULL,
    "full_address" "text",
    "latitude" double precision,
    "longitude" double precision,
    "property_address" "text"
);


ALTER TABLE "silver"."locations_df_sil" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "silver"."locations_df_sil_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "silver"."locations_df_sil_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "silver"."locations_df_sil_id_seq" OWNED BY "silver"."locations_df_sil"."id";



CREATE TABLE IF NOT EXISTS "silver"."processed_data" (
    "id" integer NOT NULL,
    "property_address" "text",
    "agent_address" "text",
    "agent_name" "text",
    "available_date" "text",
    "property_type" "text",
    "bedrooms" "text",
    "bathrooms" "text",
    "post_date" "text",
    "price" "text",
    "latitude" double precision,
    "longitude" double precision,
    "url" "text",
    "ingestion_timestamp" timestamp without time zone,
    "monthly_price" "text",
    "parsed_post_date" "text",
    "parsed_available_date" timestamp without time zone,
    "full_address" "text",
    "listing_id" "text",
    "rowid" "text"
);


ALTER TABLE "silver"."processed_data" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "silver"."processed_data_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "silver"."processed_data_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "silver"."processed_data_id_seq" OWNED BY "silver"."processed_data"."id";



CREATE TABLE IF NOT EXISTS "silver"."properties_df" (
    "id" integer NOT NULL,
    "property_type" "text",
    "bedrooms" "text",
    "bathrooms" "text",
    "rowid" "text",
    "locations_df_sil_id" integer,
    "agents_df_sil_id" integer
);


ALTER TABLE "silver"."properties_df" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "silver"."properties_df_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "silver"."properties_df_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "silver"."properties_df_id_seq" OWNED BY "silver"."properties_df"."id";



CREATE TABLE IF NOT EXISTS "silver"."properties_df_sil" (
    "id" integer NOT NULL,
    "property_type" "text",
    "bedrooms" "text",
    "bathrooms" "text",
    "locations_df_sil_id" integer,
    "agents_df_sil_id" integer
);


ALTER TABLE "silver"."properties_df_sil" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "silver"."properties_df_sil_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "silver"."properties_df_sil_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "silver"."properties_df_sil_id_seq" OWNED BY "silver"."properties_df_sil"."id";



ALTER TABLE ONLY "bronze"."rightmove_data_brz" ALTER COLUMN "id" SET DEFAULT "nextval"('"bronze"."rightmove_data_brz_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."properties" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."properties_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."query_logs" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."query_logs_id_seq"'::"regclass");



ALTER TABLE ONLY "silver"."agents_df" ALTER COLUMN "id" SET DEFAULT "nextval"('"silver"."agents_df_id_seq"'::"regclass");



ALTER TABLE ONLY "silver"."agents_df_sil" ALTER COLUMN "id" SET DEFAULT "nextval"('"silver"."agents_df_sil_id_seq"'::"regclass");



ALTER TABLE ONLY "silver"."listings_df" ALTER COLUMN "id" SET DEFAULT "nextval"('"silver"."listings_df_id_seq"'::"regclass");



ALTER TABLE ONLY "silver"."listings_df_sil" ALTER COLUMN "id" SET DEFAULT "nextval"('"silver"."listings_df_sil_id_seq"'::"regclass");



ALTER TABLE ONLY "silver"."locations_df" ALTER COLUMN "id" SET DEFAULT "nextval"('"silver"."locations_df_id_seq"'::"regclass");



ALTER TABLE ONLY "silver"."locations_df_sil" ALTER COLUMN "id" SET DEFAULT "nextval"('"silver"."locations_df_sil_id_seq"'::"regclass");



ALTER TABLE ONLY "silver"."processed_data" ALTER COLUMN "id" SET DEFAULT "nextval"('"silver"."processed_data_id_seq"'::"regclass");



ALTER TABLE ONLY "silver"."properties_df" ALTER COLUMN "id" SET DEFAULT "nextval"('"silver"."properties_df_id_seq"'::"regclass");



ALTER TABLE ONLY "silver"."properties_df_sil" ALTER COLUMN "id" SET DEFAULT "nextval"('"silver"."properties_df_sil_id_seq"'::"regclass");



ALTER TABLE ONLY "bronze"."rightmove_data_brz"
    ADD CONSTRAINT "rightmove_data_brz_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_group"
    ADD CONSTRAINT "auth_group_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_group"
    ADD CONSTRAINT "auth_group_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_permission"
    ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");



ALTER TABLE ONLY "public"."auth_permission"
    ADD CONSTRAINT "auth_permission_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_user_groups"
    ADD CONSTRAINT "auth_user_groups_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_user_groups"
    ADD CONSTRAINT "auth_user_groups_user_id_group_id_94350c0c_uniq" UNIQUE ("user_id", "group_id");



ALTER TABLE ONLY "public"."auth_user"
    ADD CONSTRAINT "auth_user_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_user_user_permissions"
    ADD CONSTRAINT "auth_user_user_permissions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_user_user_permissions"
    ADD CONSTRAINT "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" UNIQUE ("user_id", "permission_id");



ALTER TABLE ONLY "public"."auth_user"
    ADD CONSTRAINT "auth_user_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."backend_todo"
    ADD CONSTRAINT "backend_todo_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_admin_log"
    ADD CONSTRAINT "django_admin_log_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_content_type"
    ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");



ALTER TABLE ONLY "public"."django_content_type"
    ADD CONSTRAINT "django_content_type_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_migrations"
    ADD CONSTRAINT "django_migrations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_session"
    ADD CONSTRAINT "django_session_pkey" PRIMARY KEY ("session_key");



ALTER TABLE ONLY "public"."properties1"
    ADD CONSTRAINT "properties1_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."properties"
    ADD CONSTRAINT "properties_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."query_logs"
    ADD CONSTRAINT "query_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."properties"
    ADD CONSTRAINT "unique_property" UNIQUE ("property_type", "bedrooms", "bathrooms", "locations_df_sil_id", "agents_df_sil_id");



ALTER TABLE ONLY "silver"."agents_df"
    ADD CONSTRAINT "agents_df_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "silver"."agents_df_sil"
    ADD CONSTRAINT "agents_df_sil_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "silver"."listings_df"
    ADD CONSTRAINT "listings_df_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "silver"."listings_df_sil"
    ADD CONSTRAINT "listings_df_sil_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "silver"."locations_df"
    ADD CONSTRAINT "locations_df_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "silver"."locations_df_sil"
    ADD CONSTRAINT "locations_df_sil_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "silver"."processed_data"
    ADD CONSTRAINT "processed_data_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "silver"."properties_df"
    ADD CONSTRAINT "properties_df_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "silver"."properties_df_sil"
    ADD CONSTRAINT "properties_df_sil_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "silver"."agents_df"
    ADD CONSTRAINT "unique_agent_name" UNIQUE ("agent_name");



CREATE INDEX "auth_group_name_a6ea08ec_like" ON "public"."auth_group" USING "btree" ("name" "varchar_pattern_ops");



CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "public"."auth_group_permissions" USING "btree" ("group_id");



CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "public"."auth_group_permissions" USING "btree" ("permission_id");



CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "public"."auth_permission" USING "btree" ("content_type_id");



CREATE INDEX "auth_user_groups_group_id_97559544" ON "public"."auth_user_groups" USING "btree" ("group_id");



CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "public"."auth_user_groups" USING "btree" ("user_id");



CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "public"."auth_user_user_permissions" USING "btree" ("permission_id");



CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "public"."auth_user_user_permissions" USING "btree" ("user_id");



CREATE INDEX "auth_user_username_6821ab7c_like" ON "public"."auth_user" USING "btree" ("username" "varchar_pattern_ops");



CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "public"."django_admin_log" USING "btree" ("content_type_id");



CREATE INDEX "django_admin_log_user_id_c564eba6" ON "public"."django_admin_log" USING "btree" ("user_id");



CREATE INDEX "django_session_expire_date_a5c62663" ON "public"."django_session" USING "btree" ("expire_date");



CREATE INDEX "django_session_session_key_c0390e0f_like" ON "public"."django_session" USING "btree" ("session_key" "varchar_pattern_ops");



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_permission"
    ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_user_groups"
    ADD CONSTRAINT "auth_user_groups_group_id_97559544_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_user_groups"
    ADD CONSTRAINT "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_user_user_permissions"
    ADD CONSTRAINT "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_user_user_permissions"
    ADD CONSTRAINT "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."django_admin_log"
    ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."django_admin_log"
    ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "silver"."properties_df_sil"
    ADD CONSTRAINT "fk_agents_df_sil_id" FOREIGN KEY ("agents_df_sil_id") REFERENCES "silver"."agents_df_sil"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "silver"."properties_df"
    ADD CONSTRAINT "fk_agents_df_sil_id" FOREIGN KEY ("agents_df_sil_id") REFERENCES "silver"."agents_df"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "silver"."agents_df"
    ADD CONSTRAINT "fk_locations" FOREIGN KEY ("locations_df_id") REFERENCES "silver"."locations_df"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "silver"."properties_df_sil"
    ADD CONSTRAINT "fk_locations_df_sil_id" FOREIGN KEY ("locations_df_sil_id") REFERENCES "silver"."locations_df_sil"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "silver"."properties_df"
    ADD CONSTRAINT "fk_locations_df_sil_id" FOREIGN KEY ("locations_df_sil_id") REFERENCES "silver"."locations_df"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "silver"."listings_df_sil"
    ADD CONSTRAINT "fk_properties_df_sil_id" FOREIGN KEY ("properties_df_sil_id") REFERENCES "silver"."properties_df_sil"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "silver"."listings_df"
    ADD CONSTRAINT "fk_properties_df_sil_id" FOREIGN KEY ("properties_df_sil_id") REFERENCES "silver"."properties_df"("id") ON DELETE CASCADE;





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "bronze" TO "anon";
GRANT USAGE ON SCHEMA "bronze" TO "authenticated";
GRANT USAGE ON SCHEMA "bronze" TO "service_role";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT USAGE ON SCHEMA "silver" TO "anon";
GRANT USAGE ON SCHEMA "silver" TO "authenticated";
GRANT USAGE ON SCHEMA "silver" TO "service_role";

















































































































































































GRANT ALL ON FUNCTION "public"."log_queries"() TO "anon";
GRANT ALL ON FUNCTION "public"."log_queries"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."log_queries"() TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "bronze"."rightmove_data_brz" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "bronze"."rightmove_data_brz" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "bronze"."rightmove_data_brz" TO "service_role";



GRANT ALL ON SEQUENCE "bronze"."rightmove_data_brz_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "bronze"."rightmove_data_brz_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "bronze"."rightmove_data_brz_id_seq" TO "service_role";


















GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."agents_df" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."agents_df" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."agents_df" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."locations_df" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."locations_df" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."locations_df" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."agents_locations" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."agents_locations" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."agents_locations" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."auth_group" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."auth_group" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."auth_group" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_group_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_group_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_group_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."auth_group_permissions" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."auth_group_permissions" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."auth_group_permissions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_group_permissions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_group_permissions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_group_permissions_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."auth_permission" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."auth_permission" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."auth_permission" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_permission_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_permission_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_permission_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."auth_user" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."auth_user" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."auth_user" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."auth_user_groups" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."auth_user_groups" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."auth_user_groups" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_user_groups_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_user_groups_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_user_groups_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_user_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_user_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_user_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."auth_user_user_permissions" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."auth_user_user_permissions" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."auth_user_user_permissions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_user_user_permissions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_user_user_permissions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_user_user_permissions_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."backend_todo" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."backend_todo" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."backend_todo" TO "service_role";



GRANT ALL ON SEQUENCE "public"."backend_todo_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."backend_todo_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."backend_todo_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."django_admin_log" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."django_admin_log" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."django_admin_log" TO "service_role";



GRANT ALL ON SEQUENCE "public"."django_admin_log_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."django_admin_log_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."django_admin_log_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."django_content_type" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."django_content_type" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."django_content_type" TO "service_role";



GRANT ALL ON SEQUENCE "public"."django_content_type_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."django_content_type_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."django_content_type_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."django_migrations" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."django_migrations" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."django_migrations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."django_migrations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."django_migrations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."django_migrations_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."django_session" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."django_session" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."django_session" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."properties" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."properties" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."properties" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."properties1" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."properties1" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."properties1" TO "service_role";



GRANT ALL ON SEQUENCE "public"."properties_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."properties_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."properties_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."query_logs" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."query_logs" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."query_logs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."query_logs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."query_logs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."query_logs_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "silver"."agents_df_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "silver"."agents_df_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "silver"."agents_df_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."agents_df_sil" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."agents_df_sil" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."agents_df_sil" TO "service_role";



GRANT ALL ON SEQUENCE "silver"."agents_df_sil_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "silver"."agents_df_sil_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "silver"."agents_df_sil_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."listings_df" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."listings_df" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."listings_df" TO "service_role";



GRANT ALL ON SEQUENCE "silver"."listings_df_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "silver"."listings_df_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "silver"."listings_df_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."listings_df_sil" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."listings_df_sil" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."listings_df_sil" TO "service_role";



GRANT ALL ON SEQUENCE "silver"."listings_df_sil_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "silver"."listings_df_sil_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "silver"."listings_df_sil_id_seq" TO "service_role";



GRANT SELECT,USAGE ON SEQUENCE "silver"."locations_df_id_seq" TO "authenticated";
GRANT SELECT,USAGE ON SEQUENCE "silver"."locations_df_id_seq" TO "anon";
GRANT SELECT,USAGE ON SEQUENCE "silver"."locations_df_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."locations_df_sil" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."locations_df_sil" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."locations_df_sil" TO "service_role";



GRANT ALL ON SEQUENCE "silver"."locations_df_sil_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "silver"."locations_df_sil_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "silver"."locations_df_sil_id_seq" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "silver"."processed_data" TO "authenticated";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "silver"."processed_data" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "silver"."processed_data" TO "service_role";



GRANT ALL ON SEQUENCE "silver"."processed_data_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "silver"."processed_data_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "silver"."processed_data_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."properties_df" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."properties_df" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."properties_df" TO "service_role";



GRANT ALL ON SEQUENCE "silver"."properties_df_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "silver"."properties_df_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "silver"."properties_df_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."properties_df_sil" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."properties_df_sil" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "silver"."properties_df_sil" TO "service_role";



GRANT ALL ON SEQUENCE "silver"."properties_df_sil_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "silver"."properties_df_sil_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "silver"."properties_df_sil_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "bronze" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "bronze" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "bronze" GRANT ALL ON SEQUENCES TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "bronze" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "bronze" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "bronze" GRANT ALL ON FUNCTIONS TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "bronze" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "bronze" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "bronze" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "service_role";































RESET ALL;
